# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates daily
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: LightDestory
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          config_octicon: yes
          config_timezone: Europe/Rome
          repositories_forks: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: programming, markup
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 12
          plugin_languages_other: yes
          plugin_languages_recent_categories: programming, markup
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 180
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 2
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 2
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: 76561198087267527
          plugin_traffic: yes
          plugin_gists: yes
          plugin_anilist: yes
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: LightDestory
